# Generated by Django 5.2.12 on 2026-04-08 07:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(unique=True, verbose_name='Année')),
                ('est_ouvert', models.BooleanField(default=False, verbose_name='Exercice ouvert')),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('taux_t35', models.DecimalField(decimal_places=2, default=Decimal('35000'), max_digits=12, verbose_name='Taux mensuel T35 (FCFA)')),
                ('versement_t35', models.DecimalField(decimal_places=2, default=Decimal('60000'), max_digits=12, verbose_name='Versement mensuel par part T35 (FCFA)')),
                ('taux_t75', models.DecimalField(decimal_places=2, default=Decimal('75000'), max_digits=12, verbose_name='Taux mensuel T75 (FCFA)')),
                ('taux_t100', models.DecimalField(decimal_places=2, default=Decimal('100000'), max_digits=12, verbose_name='Taux mensuel T100 (FCFA)')),
                ('diviseur_interet_t35', models.IntegerField(default=35, verbose_name='Diviseur intérêts T35 (nb parts)')),
                ('seuil_eligibilite_interets', models.DecimalField(decimal_places=2, default=Decimal('900000'), max_digits=12, verbose_name='Seuil éligibilité intérêts fonds (FCFA)')),
                ('fonds_roulement_mensuel', models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=10, verbose_name='Fonds de roulement / adhérent / mois (FCFA)')),
                ('frais_exceptionnels_mensuel', models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=10, verbose_name='Frais exceptionnels / adhérent / mois (FCFA)')),
                ('collation_mensuelle', models.DecimalField(decimal_places=2, default=Decimal('4000'), max_digits=10, verbose_name='Collation / adhérent / mois (FCFA)')),
                ('mutuelle_mensuelle', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Cotisation mutuelle mensuelle / adhérent (FCFA)')),
                ('montant_inscription', models.DecimalField(decimal_places=2, default=Decimal('25000'), max_digits=10, verbose_name="Frais d'inscription nouvel adhérent (FCFA)")),
                ('complement_fonds_fin_exercice', models.DecimalField(decimal_places=2, default=Decimal('100000'), max_digits=12, verbose_name="Complément fonds fin d'exercice (FCFA)")),
                ('penalite_especes', models.DecimalField(decimal_places=2, default=Decimal('3000'), max_digits=10, verbose_name='Pénalité versement espèces (FCFA)')),
                ('penalite_especes_active', models.BooleanField(default=True, verbose_name='Pénalité espèces active')),
                ('pourcentage_penalite_echec', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=5, verbose_name='% pénalité échec tontine')),
                ('nb_echecs_max_avant_liste_rouge', models.IntegerField(default=3, verbose_name="Nb max d'échecs avant liste rouge")),
                ('taux_interet_pret_mensuel', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=5, verbose_name='Taux intérêt prêt (%/mois)')),
                ('majoration_retard_mois_1', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=5, verbose_name='Majoration retard prêt mois 1 (%)')),
                ('majoration_retard_mois_2', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5, verbose_name='Majoration retard prêt mois 2 (%)')),
                ('montant_min_pret', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Montant minimum prêt (FCFA)')),
                ('montant_max_pret', models.DecimalField(decimal_places=2, default=Decimal('2000000'), max_digits=12, verbose_name='Montant maximum prêt (FCFA)')),
                ('contribution_foyer_lot_principal', models.DecimalField(decimal_places=2, default=Decimal('150000'), max_digits=12, verbose_name='Contribution foyer sur lot principal (FCFA)')),
                ('complement_mutuelle_fin_exercice', models.DecimalField(decimal_places=2, default=Decimal('30000'), max_digits=12, verbose_name="Complément mutuelle fin d'exercice (FCFA)")),
            ],
            options={
                'verbose_name': 'Configuration exercice',
                'verbose_name_plural': 'Configurations exercices',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='AutreDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('libelle', models.CharField(max_length=300, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant (FCFA)')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autres_depenses', to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Autre dépense',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DepenseCollation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de la séance')),
                ('libelle', models.CharField(default='COLLATION SEANCE', max_length=300, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant (FCFA)')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_collation', to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Dépense collation',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DepenseFondsRoulement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('libelle', models.CharField(max_length=300, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant (FCFA)')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_fonds_roulement', to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Dépense fonds de roulement',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DepenseFoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du virement')),
                ('libelle', models.CharField(default='VERSE DANS LE COMPTE CONSEIL', max_length=300, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant (FCFA)')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_foyer', to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Dépense foyer',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DepenseFraisExceptionnels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('libelle', models.CharField(max_length=300, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant (FCFA)')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_frais_exceptionnels', to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Dépense frais exceptionnels',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AgioBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(verbose_name='Mois (1-12)')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('montant_agio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Agio / frais bancaires (FCFA)')),
                ('interet_crediteur', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Intérêt créditeur banque (FCFA)')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agios', to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Agio bancaire',
                'ordering': ['annee', 'mois'],
                'unique_together': {('mois', 'annee')},
            },
        ),
    ]
