# Generated by Django 5.2.12 on 2026-04-08 07:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeRouge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField(auto_now_add=True)),
                ('motif', models.TextField()),
                ('montant_dette', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_garantie', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('est_solde', models.BooleanField(default=False)),
                ('date_solde', models.DateField(blank=True, null=True)),
                ('adherent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='liste_rouge', to='adherents.adherent')),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Liste rouge',
            },
        ),
        migrations.CreateModel(
            name='RemboursementDette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observations', models.TextField(blank=True)),
                ('liste_rouge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='dettes.listerouge')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
