# Generated by Django 5.2.12 on 2026-05-11 08:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        ('fonds', '0001_initial'),
        ('parametrage', '0001_initial'),
        ('saisie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement_tontine', models.CharField(blank=True, max_length=20)),
                ('num_cheque_versement', models.CharField(blank=True, max_length=50)),
                ('mode_paiement_lot', models.CharField(blank=True, max_length=20)),
                ('num_cheque_lot', models.CharField(blank=True, max_length=50)),
                ('num_cheque_petit_lot', models.CharField(blank=True, max_length=50)),
                ('mode_remb_petit_lot', models.CharField(blank=True, max_length=20)),
                ('autres_mode_verst', models.CharField(blank=True, max_length=100)),
                ('numero_cheque_effectif', models.CharField(blank=True, max_length=50)),
                ('epargne_assurance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('montant_cheque_effectif', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('interet_pret', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('nbre_mois_pret', models.IntegerField(default=0)),
                ('montant_depense', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('penalite_pret_fonds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('remboursement_transport', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('pret_definitif', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('nombre_mois_pret', models.IntegerField(default=0)),
                ('date_remboursement', models.CharField(blank=True, max_length=30)),
                ('statut_pret', models.CharField(blank=True, max_length=20)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complements_historique', to='adherents.adherent')),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
                ('tableau_bord', models.OneToOneField(help_text='Lie ce complément au TableauDeBord existant', on_delete=django.db.models.deletion.PROTECT, related_name='complement_historique', to='saisie.saisiemonthly')),
            ],
            options={
                'verbose_name': 'Complément Historique',
                'ordering': ['tableau_bord__annee', 'tableau_bord__mois', 'adherent__numero_ordre'],
            },
        ),
        migrations.CreateModel(
            name='ComplementMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interet_pret_fonds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('numero_cheque_versement', models.CharField(blank=True, help_text='N° chèque du versement mensuel (col 20 AUTREMOUVEMENT)', max_length=50)),
                ('remboursement_pret_fonds', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant remboursé ce mois (col 21)', max_digits=14)),
                ('mode_versement_remboursement', models.CharField(blank=True, help_text='BANQUE/ESPECES/ECHEC (col 22)', max_length=20)),
                ('mode_versement_pret', models.CharField(blank=True, help_text='Mode de versement du prêt (col 23)', max_length=20)),
                ('numero_cheque_pret', models.CharField(blank=True, help_text='N° chèque du prêt (col 24)', max_length=50)),
                ('penalite_pret_fonds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('penalite_fonds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('penalite_echec_tontine', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('penalite_retard_tontine', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('remboursement_transport', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('depense_fonds_roulement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('depense_frais_exceptionnel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('depense_fonds_mutuelle', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('depense_collation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('depense_penalite_banque', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('pret_definitif', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('date_remboursement', models.CharField(blank=True, max_length=30)),
                ('statut_pret', models.CharField(blank=True, max_length=20)),
                ('don_volontaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complements_mouvement', to='adherents.adherent')),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
                ('mouvement_fonds', models.OneToOneField(help_text='Lie ce complément au MouvementFonds existant (même adhérent/mois/annee)', on_delete=django.db.models.deletion.PROTECT, related_name='complement', to='fonds.mouvementfonds')),
                ('tableau_bord', models.OneToOneField(help_text='Lie ce complément au TableauDeBord existant', on_delete=django.db.models.deletion.PROTECT, related_name='complement_mouvement', to='saisie.saisiemonthly')),
            ],
            options={
                'verbose_name': 'Complément Mouvement',
                'ordering': ['mouvement_fonds__annee', 'mouvement_fonds__mois', 'adherent__numero_ordre'],
            },
        ),
    ]
