# Generated by Django 5.2.12 on 2026-05-11 08:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheseCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_fonds_caisse', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('entrees_fonds_caisse', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sorties_fonds_caisse', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('report_fonds_roulement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('entrees_fonds_roulement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sorties_fonds_roulement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('report_frais_exceptionnels', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('entrees_frais_excep', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sorties_frais_excep', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('report_mutuelle', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('entrees_mutuelle', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sorties_mutuelle', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('report_inscription', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('entrees_inscription', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('report_penalites', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('entrees_penalites', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sorties_penalites', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('report_sanctions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('entrees_sanctions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sorties_sanctions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('report_collation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('entrees_collation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sorties_collation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('report_interet_bancaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sorties_interet_bancaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('report_foyer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('entrees_foyer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sorties_foyer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('report_terrain', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('entrees_terrain', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sorties_terrain', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('report_interet_epargne', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sorties_interet_epargne', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('report_aides_lagwe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sorties_aides_lagwe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('report_depot_tchouamo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sorties_depot_tchouamo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('compte_cca', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Solde compte CCA', max_digits=14, verbose_name='Compte CCA')),
                ('compte_mc2', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Compte MC² (non actualisé)')),
                ('compte_afriland', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Compte AFRILAND')),
                ('dette_prefinancement_lagwe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name="Dette préfinancement LA'AGWEU")),
                ('dette_mr_kouatcho', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Dette Mr KOUATCHO')),
                ('reste_a_recuperer_conseil', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Reste à récupérer au conseil')),
                ('dettes_tontines', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Dettes tontines')),
                ('autres_disponibilites', models.TextField(blank=True, default='', verbose_name='Autres disponibilités (libellé + montant)')),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('config_exercice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
        ),
        migrations.CreateModel(
            name='FicheCassation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonds_caisse', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('repartition_interets', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('epargne_cumulee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('repartition_penalites', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('repartition_collation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sanctions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('complement_mutuelle', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('complement_fonds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('dette_pret', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('dons_foyer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('montant_percu', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('montant_percu_especes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('montant_percu_cheque', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('reconduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('nouveau_fonds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('est_validee', models.BooleanField(default=False)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_cassation', to='adherents.adherent')),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Fiche de cassation',
                'unique_together': {('adherent', 'config_exercice')},
            },
        ),
    ]
