# Generated by Django 5.2.12 on 2026-04-08 07:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheseCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_fonds_caisse', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('entrees_fonds_caisse', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sorties_fonds_caisse', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('report_fonds_roulement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('entrees_fonds_roulement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sorties_fonds_roulement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('report_frais_exceptionnels', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('entrees_frais_excep', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sorties_frais_excep', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('report_mutuelle', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('entrees_mutuelle', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sorties_mutuelle', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('report_inscription', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('entrees_inscription', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('report_penalites', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('entrees_penalites', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sorties_penalites', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('report_collation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('entrees_collation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sorties_collation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('report_foyer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('entrees_foyer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sorties_foyer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('config_exercice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
        ),
        migrations.CreateModel(
            name='FicheCassation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonds_caisse', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('repartition_interets', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('epargne_cumulee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('repartition_penalites', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('repartition_collation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sanctions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('complement_mutuelle', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('complement_fonds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('dette_pret', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('dons_foyer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('montant_percu', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('montant_percu_especes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('montant_percu_cheque', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('reconduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('nouveau_fonds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('est_validee', models.BooleanField(default=False)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_cassation', to='adherents.adherent')),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Fiche de cassation',
                'unique_together': {('adherent', 'config_exercice')},
            },
        ),
    ]
