# Generated by Django 5.2.12 on 2026-04-12 13:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthesecompte',
            name='autres_disponibilites',
            field=models.TextField(blank=True, default='', verbose_name='Autres disponibilités (libellé + montant)'),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='compte_afriland',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Compte AFRILAND'),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='compte_cca',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Solde compte CCA', max_digits=14, verbose_name='Compte CCA'),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='compte_mc2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Compte MC² (non actualisé)'),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='dette_mr_kouatcho',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Dette Mr KOUATCHO'),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='dette_prefinancement_lagwe',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name="Dette préfinancement LA'AGWEU"),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='dettes_tontines',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Dettes tontines'),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='entrees_sanctions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='entrees_terrain',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='report_aides_lagwe',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='report_depot_tchouamo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='report_interet_bancaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='report_interet_epargne',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='report_sanctions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='report_terrain',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='reste_a_recuperer_conseil',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Reste à récupérer au conseil'),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='sorties_aides_lagwe',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='sorties_depot_tchouamo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='sorties_interet_bancaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='sorties_interet_epargne',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='sorties_sanctions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='synthesecompte',
            name='sorties_terrain',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
    ]
