# Generated by Django 5.2.12 on 2026-04-08 07:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('taux_mensuel', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nombre_mois', models.IntegerField()),
                ('interet_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_total_du', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_octroi', models.DateField()),
                ('date_echeance', models.DateField()),
                ('mode_versement', models.CharField(choices=[('BANQUE', 'Banque'), ('ESPECES', 'Espèces')], max_length=10)),
                ('numero_cheque', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('SOLDE', 'Soldé'), ('LISTE_NOIRE', 'Liste noire')], default='EN_COURS', max_length=15)),
                ('nb_mois_retard', models.IntegerField(default=0)),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('est_demande_membre', models.BooleanField(default=False)),
                ('est_valide_bureau', models.BooleanField(default=False)),
                ('motif_demande', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prets', to='adherents.adherent')),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Prêt',
                'ordering': ['-date_octroi'],
            },
        ),
        migrations.CreateModel(
            name='RemboursementPret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode_versement', models.CharField(choices=[('BANQUE', 'Banque'), ('ESPECES', 'Espèces')], max_length=10)),
                ('numero_cheque', models.CharField(blank=True, max_length=50)),
                ('penalite_retard', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='prets.pret')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'ordering': ['annee', 'mois'],
            },
        ),
    ]
