# Generated by Django 5.2.12 on 2026-04-08 07:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableauDeBord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('versement_banque', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('versement_especes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('autre_versement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('complement_epargne', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('mode_versement', models.CharField(choices=[('BANQUE', 'Banque'), ('ESPECES', 'Espèces'), ('ECHEC', 'Échec')], default='ECHEC', max_length=10)),
                ('inscription', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('mutuelle', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('contribution_foyer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('don_foyer_volontaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sanction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('pret_fonds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('remboursement_pret', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('mode_pret', models.CharField(blank=True, choices=[('BANQUE', 'Banque'), ('ESPECES', 'Espèces'), ('ECHEC', 'Échec')], max_length=10)),
                ('numero_cheque_pret', models.CharField(blank=True, max_length=50)),
                ('retrait_partiel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('bonus_malus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('montant_engagement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('penalite_especes_appli', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('penalite_echec_appli', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('contribution_foyer_auto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('reste', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('libelle_depense', models.CharField(blank=True, max_length=200)),
                ('compte_depense', models.CharField(blank=True, max_length=100)),
                ('autres_depenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('est_valide', models.BooleanField(default=False)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adherents.adherent')),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Tableau de bord mensuel',
                'ordering': ['annee', 'mois', 'adherent__numero_ordre'],
                'unique_together': {('adherent', 'mois', 'annee')},
            },
        ),
    ]
