# Generated by Django 5.2.12 on 2026-05-11 08:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaisieMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('nbre_lots_t60', models.IntegerField(default=0, help_text='TABBORD col J — nbre parts T60')),
                ('nbre_lots_t75', models.IntegerField(default=0, help_text='TABBORD col L — nbre parts T75')),
                ('nbre_lots_t100', models.IntegerField(default=0, help_text='TABBORD col N — nbre parts T100')),
                ('achat_lot_t60', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col AC — intérêt offert sur lot T60', max_digits=12)),
                ('achat_lot_t75', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col AD — intérêt offert sur lot T75', max_digits=12)),
                ('achat_lot_t100', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col AE — intérêt offert sur lot T100', max_digits=12)),
                ('mode_paiement_lot', models.CharField(blank=True, choices=[('BANQUE', 'Banque'), ('ESPECES', 'Espèces'), ('ECHEC', 'Échec')], help_text='Col AF', max_length=10)),
                ('vente_petit_lot_t60', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col AI', max_digits=12)),
                ('vente_petit_lot_t75', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col AJ', max_digits=12)),
                ('vente_petit_lot_t100', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col AK', max_digits=12)),
                ('interet_petit_lot_t60', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col AL', max_digits=10)),
                ('interet_petit_lot_t75', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col AM', max_digits=10)),
                ('interet_petit_lot_t100', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col AN', max_digits=10)),
                ('mode_remb_petit_lot', models.CharField(blank=True, choices=[('BANQUE', 'Banque'), ('ESPECES', 'Espèces'), ('ECHEC', 'Échec')], help_text='Col AP', max_length=10)),
                ('remboursement_pret', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col S — remboursement prêt ce mois', max_digits=14)),
                ('mode_remb_pret', models.CharField(blank=True, choices=[('BANQUE', 'Banque'), ('ESPECES', 'Espèces'), ('ECHEC', 'Échec')], help_text='Col T', max_length=10)),
                ('pret_fonds', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col Z — nouveau prêt octroyé ce mois', max_digits=14)),
                ('mode_paiement_pret', models.CharField(blank=True, choices=[('BANQUE', 'Banque'), ('ESPECES', 'Espèces'), ('ECHEC', 'Échec')], help_text='Col AA', max_length=10)),
                ('nbre_mois_pret', models.IntegerField(default=0, help_text='Col BG — nombre de mois écoulés (pour calcul intérêt prêt)')),
                ('complement_epargne', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col G — peut être négatif (malus)', max_digits=14)),
                ('montant_especes', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col BA — montant espèces cas particuliers', max_digits=14)),
                ('numero_cheque', models.CharField(blank=True, help_text="Col BE — numéro chèque effectif ou 'OK'", max_length=50)),
                ('libelle_depense', models.CharField(blank=True, help_text='Col BO — ex: ACHAT FOURNITURE', max_length=200)),
                ('compte_depense', models.CharField(blank=True, help_text='Col BP — ex: FONDS DE ROULEMENT', max_length=100)),
                ('montant_depense', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col BQ', max_digits=12)),
                ('depense_collation', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col BK — dépense collation (rare)', max_digits=12)),
                ('sanction', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col V', max_digits=12)),
                ('inscription', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col W — nouvel adhérent', max_digits=12)),
                ('retrait_partiel', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col AV', max_digits=14)),
                ('mutuelle', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col AT', max_digits=12)),
                ('contribution_foyer', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col BB — contribution foyer volontaire', max_digits=12)),
                ('penalite_pret_fonds', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col BL', max_digits=12)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saisies_monthly', to='adherents.adherent')),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Saisie mensuelle',
                'verbose_name_plural': 'Saisies mensuelles',
                'ordering': ['annee', 'mois', 'adherent__numero_ordre'],
                'unique_together': {('adherent', 'mois', 'annee')},
            },
        ),
    ]
