# Generated by Django 5.2.12 on 2026-04-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableaudebord',
            name='penalite_especes_appliquee',
            field=models.BooleanField(default=False, help_text='Cocher pour appliquer la pénalité espèces (décision du bureau)', verbose_name='Appliquer pénalité espèces'),
        ),
    ]
