# Generated by Django 5.2.12 on 2026-04-08 07:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AideMutuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('evenement', models.CharField(max_length=300)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aides_mutuelle', to='adherents.adherent')),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Aide mutuelle',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CotisationMutuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotisations_mutuelle', to='adherents.adherent')),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Cotisation mutuelle',
                'ordering': ['annee', 'mois'],
                'unique_together': {('adherent', 'mois', 'annee')},
            },
        ),
    ]
