# Generated by Django 5.2.12 on 2026-04-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('numero_ordre', models.IntegerField(unique=True)),
                ('nom_prenom', models.CharField(max_length=200)),
                ('fonction', models.CharField(blank=True, max_length=200)),
                ('telephone1', models.CharField(blank=True, max_length=25)),
                ('telephone2', models.CharField(blank=True, max_length=25)),
                ('residence', models.CharField(blank=True, max_length=200)),
                ('date_adhesion', models.DateField(blank=True, null=True)),
                ('date_reception', models.DateField(blank=True, null=True, verbose_name='Date 1ère réception')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='adherents/')),
                ('poste_bureau', models.CharField(blank=True, default='', max_length=100, verbose_name='Poste au bureau')),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adhérent',
                'verbose_name_plural': 'Adhérents',
                'ordering': ['numero_ordre'],
            },
        ),
    ]
