# Generated by Django 5.2.12 on 2026-04-12 13:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='capital_depart_exercice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Capital composé fin d'exercice précédent. Sert de base au calcul du fonds définitif mois 1 de l'exercice suivant. Mis à jour automatiquement à la clôture.", max_digits=14, verbose_name='Capital de départ (prochain exercice)'),
        ),
    ]
