# Generated by Django 5.2.12 on 2026-04-08 07:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauTontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('taux_mensuel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('versement_mensuel_par_part', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diviseur_interet', models.IntegerField(default=1)),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveaux_tontine', to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Niveau tontine',
                'ordering': ['taux_mensuel'],
                'unique_together': {('config_exercice', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SessionTontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('date_seance', models.DateField()),
                ('montant_interet_bureau', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Montant intérêts décidé par le bureau')),
                ('est_cloturee', models.BooleanField(default=False)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='tontines.niveautontine')),
            ],
            options={
                'verbose_name': 'Session tontine',
                'ordering': ['annee', 'mois'],
                'unique_together': {('niveau', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='ParticipationTontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parts', models.IntegerField(default=1)),
                ('mode_versement', models.CharField(choices=[('BANQUE', 'Banque'), ('ESPECES', 'Espèces'), ('ECHEC', 'Échec')], default='ECHEC', max_length=10)),
                ('montant_verse', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('penalite_especes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('penalite_echec', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('nb_echecs_cumules', models.IntegerField(default=0)),
                ('en_liste_rouge', models.BooleanField(default=False)),
                ('complement_epargne', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('numero_cheque', models.CharField(blank=True, max_length=50)),
                ('a_obtenu_lot_principal', models.BooleanField(default=False)),
                ('montant_lot_principal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('interet_lot_principal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('vente_petit_lot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('interet_petit_lot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('remboursement_petit_lot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('mode_remboursement_petit_lot', models.CharField(blank=True, choices=[('BANQUE', 'Banque'), ('ESPECES', 'Espèces'), ('ECHEC', 'Échec')], max_length=10)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations_tontine', to='adherents.adherent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='tontines.sessiontontine')),
            ],
            options={
                'verbose_name': 'Participation tontine',
                'unique_together': {('session', 'adherent')},
            },
        ),
    ]
