# Generated by Django 5.2.12 on 2026-04-08 07:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementFonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('reconduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('retrait_partiel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('capital_compose_precedent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('reste', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('epargne_nette', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('fonds_roulement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('frais_exceptionnels', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('collation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('fonds_definitif', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('base_calcul_interet', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('interet_attribue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('capital_compose', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sanction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_fonds', to='adherents.adherent')),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Mouvement fonds',
                'verbose_name_plural': 'Mouvements fonds',
                'ordering': ['annee', 'mois'],
                'unique_together': {('adherent', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='ReserveMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('pool_interets', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_bases_eligibles', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('nb_adherents_eligibles', models.IntegerField(default=0)),
                ('est_reparti', models.BooleanField(default=False)),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
            options={
                'ordering': ['annee', 'mois'],
                'unique_together': {('mois', 'annee')},
            },
        ),
    ]
