# Generated by Django 5.2.12 on 2026-04-08 07:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionFoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('montant_auto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='150 000 FCFA si lot principal obtenu', max_digits=12)),
                ('don_volontaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions_foyer', to='adherents.adherent')),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Contribution foyer',
                'unique_together': {('adherent', 'mois', 'annee')},
            },
        ),
    ]
