# Generated by Django 5.2.12 on 2026-04-08 07:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('numero', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('affectation', models.CharField(max_length=200)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='adherents.adherent')),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Chèque',
                'ordering': ['annee', 'mois'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('versement_tontine', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('versement_especes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('versement_banque', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('autre_versement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('montant_engagement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('agio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historique_bancaire', to='adherents.adherent')),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Historique bancaire',
                'unique_together': {('adherent', 'mois', 'annee')},
            },
        ),
    ]
