# Generated by Django 5.2.12 on 2026-05-11 08:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgioBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('affectation', models.CharField(blank=True, max_length=200)),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
            options={
                'ordering': ['annee', 'mois'],
            },
        ),
        migrations.CreateModel(
            name='ReleveBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('versement_banque', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col E — chèques/virements', max_digits=14)),
                ('versement_especes', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col D — espèces', max_digits=14)),
                ('autre_versement', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col F — versements exceptionnels', max_digits=14)),
                ('agio', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Col H — frais bancaires du mois', max_digits=10)),
                ('est_valide_membre', models.BooleanField(default=False, help_text='Soumis par le membre depuis son espace')),
                ('est_valide_bureau', models.BooleanField(default=True, help_text='Validé par le bureau (False = en attente)')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releves_bancaires', to='adherents.adherent')),
                ('config_exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.configexercice')),
            ],
            options={
                'verbose_name': 'Relevé bancaire',
                'verbose_name_plural': 'Relevés bancaires',
                'ordering': ['annee', 'mois', 'adherent__numero_ordre'],
                'unique_together': {('adherent', 'mois', 'annee')},
            },
        ),
    ]
