# Generated by Django 5.2.12 on 2026-04-18 11:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquebancaire',
            name='en_compte_reel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant constaté en compte', max_digits=14, verbose_name='En compte'),
        ),
        migrations.AddField(
            model_name='historiquebancaire',
            name='montant_a_justifier_saisi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Écart à justifier', max_digits=14, verbose_name='Montant à justifier'),
        ),
    ]
